import { RunService } from "@rbxts/services";

/**
 * Metadata exposed by the Flamework transformer.
 */
export namespace Metadata {
	/**
	 * Runtime metadata generated by the transformer
	 */
	export interface Config {
		logLevel?: "none" | "verbose";
		profiling?: boolean;
		disableDependencyWarnings?: boolean;
	}

	/**
	 * Runtime metadata generated by the transformer
	 */
	interface ConfigContainer {
		game?: Config;
		packages: Map<string, Config>;
	}

	/**
	 * Runtime metadata generated by the transformer
	 */
	interface GlobContainer {
		game?: Map<string, string[][]>;
		packages: Map<string, Map<string, string[][]>>;
	}

	function getContainer<T>(name: string) {
		let current: Instance | undefined = script;
		while (current) {
			const flamework = current.FindFirstChild("flamework");
			if (flamework) {
				const metadata = flamework.FindFirstChild(name);
				if (metadata) {
					return require(metadata as ModuleScript) as T;
				}
			}

			current = current.Parent;
		}
	}

	function getConfig(packageId?: string) {
		return packageId === undefined ? configContainer?.game : configContainer?.packages.get(packageId);
	}

	export const configContainer = getContainer<ConfigContainer>("config");
	export const globContainer = getContainer<GlobContainer>("globs");

	export const gameConfig = configContainer?.game ?? {};

	export function getGlob(glob: string, packageId?: string) {
		const globs = packageId === undefined ? globContainer?.game : globContainer?.packages.get(packageId);
		return globs?.get(glob);
	}

	export function getLogLevel(packageId?: string) {
		const config = getConfig(packageId);
		if (!config || config.logLevel === undefined) return "none";

		return config.logLevel;
	}

	export function isProfiling(packageId?: string) {
		const config = getConfig(packageId);
		if (!config || config.profiling === undefined) return RunService.IsStudio();

		return config.profiling;
	}
}
